// `wize-dev-kit document-project` — CLI command entry point.
//
// Parses mode + flags and delegates to the appropriate scan implementation.
// Non-quick modes are stubs here; later stories fill them in.

'use strict';

const fs = require('node:fs');
const path = require('node:path');

const VALID_MODES = new Set(['quick', 'initial_scan', 'full_rescan', 'deep_dive']);

function parseMode(args) {
  let mode = 'quick';
  let resume = false;

  for (const arg of args) {
    if (arg === '--resume') {
      resume = true;
      continue;
    }
    if (arg.startsWith('--')) {
      return { mode: null, error: `unknown option: ${arg}` };
    }
    if (mode === 'quick') {
      mode = arg;
    } else {
      return { mode: null, error: `unexpected extra argument: ${arg}` };
    }
  }

  if (!VALID_MODES.has(mode)) {
    return { mode: null, error: `unknown mode: ${mode}. Valid modes: ${[...VALID_MODES].join(', ')}` };
  }

  return { mode, resume };
}

function writeBaselineFiles(projectRoot) {
  const dir = path.join(projectRoot, '.wize/knowledge/document-project');
  fs.mkdirSync(dir, { recursive: true });
  const now = new Date().toISOString().slice(0, 10);
  const files = [
    'overview.md',
    'architecture-snapshot.md',
    'conventions.md',
    'dependencies.md',
    'risk-spots.md',
    'open-questions.md'
  ];
  for (const name of files) {
    const file = path.join(dir, name);
    if (fs.existsSync(file)) continue;
    fs.writeFileSync(file, `---\nstatus: baseline\nowner: Pepper Potts + Peggy Carter\ncreated: ${now}\nlast_refreshed: ${now}\n---\n\n# ${name.replace('.md', '').replace(/-/g, ' ')}\n\n_(Baseline placeholder generated by E01-S01.)\n`, 'utf-8');
  }
}

function cmdDocumentProject({ kitRoot, projectRoot, args = [], opts = {} }) {
  const log = opts.log || console.log;
  const parsed = parseMode(args);

  if (parsed.mode === null) {
    log(parsed.error);
    return { ok: false, error: parsed.error, exitCode: 1 };
  }

  if (parsed.mode === 'quick') {
    writeBaselineFiles(projectRoot);
    log(`Documented project (quick mode) in ${path.join(projectRoot, '.wize/knowledge/document-project')}`);
    return { ok: true, mode: 'quick', changed: true };
  }

  // Stub: non-quick modes are implemented in later stories.
  log(`document-project ${parsed.mode} not yet implemented (stub)`);
  return { ok: true, mode: parsed.mode, resume: parsed.resume, changed: false };
}

module.exports = { cmdDocumentProject, parseMode };
