// GitHub Copilot adapter — emits two trees, mirroring how Copilot itself
// separates skills from agents:
//
//   - .github/skills/wize-{code}/SKILL.md    workflows + skills → agent skills
//   - .github/agents/wize-{code}.agent.md    personas → custom agents
//
// GitHub Copilot reads project agent skills from .github/skills/, .claude/skills/
// or .agents/skills/ (Agent Skills standard: a folder per skill, SKILL.md with
// `name` + `description` frontmatter, optional companion files), and custom
// agents from .github/agents/*.agent.md. Both paths are honored by agent mode
// in VS Code, the Copilot cloud agent on github.com, Copilot code review, the
// GitHub Copilot CLI and the Copilot app.
//
// Always-on instructions are NOT duplicated here: Copilot reads the root
// AGENTS.md (generated by the generic adapter) as agent instructions, so
// writing a .github/copilot-instructions.md would only fork the same content.
//
// Skills: https://docs.github.com/en/copilot/concepts/agents/about-agent-skills
// Agents: https://docs.github.com/en/copilot/how-tos/copilot-on-github/customize-copilot/customize-cloud-agent/create-custom-agents

'use strict';

const fs = require('node:fs');
const path = require('node:path');
const {
  collectAssets,
  renderAnthropicSkills,
  escapeYamlDouble,
  clipOneLine,
  ensureDir
} = require('../../tools/installer/render-shared.js');

function render(kitRoot, projectRoot, opts = {}) {
  const skillsDir = path.join(projectRoot, '.github', 'skills');
  const agentsDir = path.join(projectRoot, '.github', 'agents');

  // 1. Workflows + skills → .github/skills/wize-{code}/SKILL.md
  //    (companion files — steps/, templates/, data/ — are copied alongside by
  //    the shared emitter so micro-file workflows resolve their relative paths.)
  const skills = renderAnthropicSkills(kitRoot, skillsDir, { ...opts, kinds: ['workflow', 'skill'] });
  const written = [...skills.written];
  const skipped = [...(skills.skipped || [])];

  // 2. Personas → .github/agents/wize-{code}.agent.md
  //    Frontmatter: name (the stable wize-* identifier), description (persona
  //    name + role + summary, shown as the chat placeholder). `tools` is left
  //    out on purpose — the persona body defines the role, and omitting the
  //    property grants the agent every available tool (per GitHub docs).
  const agents = collectAssets(kitRoot, opts).filter(a => a.kind === 'agent');
  if (!opts.dryRun) ensureDir(agentsDir);

  for (const a of agents) {
    const desc = clipOneLine(`${a.name} (${a.title}) — ${a.description}`);
    const content = [
      '---',
      `name: ${a.code}`,
      `description: "${escapeYamlDouble(desc)}"`,
      '---',
      '',
      `# ${a.name} — ${a.title}`,
      '',
      a.body.trim(),
      ''
    ].join('\n');

    if (opts.dryRun) {
      written.push(`[dry-run] ${a.code}.agent.md`);
      continue;
    }
    fs.writeFileSync(path.join(agentsDir, `${a.code}.agent.md`), content, 'utf-8');
    written.push(`${a.code}.agent.md`);
  }

  return { written, skipped };
}

module.exports = { render };
