// Master index renderer for `wize-dev-kit document-project`.
//
// Generates `.wize/knowledge/document-project/index.md` linking all docs.

'use strict';

const fs = require('node:fs');
const path = require('node:path');

function link(name, file) {
  return `- [${name}](./${file})`;
}

function linkWithMarker(name, file, exists) {
  const base = link(name, file);
  return exists ? base : `${base} _(To be generated)_`;
}

function renderIndex(projectRoot, { projectTypes = [], parts = [], generated = [], existing = [], deepDiveFiles = [] } = {}) {
  const dir = path.join(projectRoot, '.wize', 'knowledge', 'document-project');
  fs.mkdirSync(dir, { recursive: true });

  const generatedSet = new Set(generated.map(g => path.basename(g)));
  const existingSet = new Set(existing.map(e => path.basename(e)));
  const has = name => generatedSet.has(name) || existingSet.has(name);

  const isMultiPart = parts.length >= 2;
  const primaryType = projectTypes[0] || 'unknown';

  const lines = [
    '---',
    'status: baseline',
    'owner: Pepper Potts + Peggy Carter',
    `created: ${new Date().toISOString().slice(0, 10)}`,
    `last_refreshed: ${new Date().toISOString().slice(0, 10)}`,
    '---',
    '',
    '# Project Documentation Index',
    '',
    `**Type:** ${isMultiPart ? 'multi-part' : primaryType}`,
    `**Primary project type(s):** ${projectTypes.join(', ') || 'unknown'}`,
    '',
    '## Generated Documentation',
    '',
    link('Project Overview', 'project-overview.md'),
    linkWithMarker('Source Tree Analysis', 'source-tree-analysis.md', has('source-tree-analysis.md')),
  ];

  if (isMultiPart) {
    for (const part of parts) {
      const suffix = part.part_id === 'root' ? '' : `-${part.part_id}`;
      lines.push(linkWithMarker(`Architecture — ${part.part_id || 'root'}`, `architecture${suffix}.md`, has(`architecture${suffix}.md`)));
      lines.push(linkWithMarker(`Development Guide — ${part.part_id || 'root'}`, `development-guide${suffix}.md`, has(`development-guide${suffix}.md`)));
      lines.push(linkWithMarker(`Component Inventory — ${part.part_id || 'root'}`, `component-inventory${suffix}.md`, has(`component-inventory${suffix}.md`)));
      lines.push(linkWithMarker(`API Contracts — ${part.part_id || 'root'}`, `api-contracts${suffix}.md`, has(`api-contracts${suffix}.md`)));
      lines.push(linkWithMarker(`Data Models — ${part.part_id || 'root'}`, `data-models${suffix}.md`, has(`data-models${suffix}.md`)));
    }
    lines.push(linkWithMarker('Integration Architecture', 'integration-architecture.md', has('integration-architecture.md')));
  } else {
    lines.push(linkWithMarker('Architecture', 'architecture.md', has('architecture.md')));
    lines.push(linkWithMarker('Development Guide', 'development-guide.md', has('development-guide.md')));
    lines.push(linkWithMarker('Component Inventory', 'component-inventory.md', has('component-inventory.md')));
    lines.push(linkWithMarker('API Contracts', 'api-contracts.md', has('api-contracts.md')));
    lines.push(linkWithMarker('Data Models', 'data-models.md', has('data-models.md')));
  }

  lines.push(linkWithMarker('Deployment Guide', 'deployment-guide.md', has('deployment-guide.md')));
  lines.push(linkWithMarker('Contribution Guide', 'contribution-guide.md', has('contribution-guide.md')));
  if (deepDiveFiles.length) {
    lines.push('', '## Deep-Dive Docs', '');
    for (const f of deepDiveFiles) {
      lines.push(link(f.replace(/^deep-dive-/, '').replace(/\.md$/, ''), f));
    }
  } else {
    lines.push(linkWithMarker('Deep-Dive Docs', 'deep-dive/', false)); // directory marker
  }

  if (existing.length) {
    lines.push('', '## Existing Documentation', '');
    for (const doc of existing) {
      const rel = path.relative(dir, doc);
      lines.push(`- [${path.basename(doc)}](./${rel})`);
    }
  }

  lines.push('', '## Brownfield Baseline', '');
  lines.push(link('Overview', 'overview.md'));
  lines.push(link('Architecture Snapshot', 'architecture-snapshot.md'));
  lines.push(link('Conventions', 'conventions.md'));
  lines.push(link('Dependencies', 'dependencies.md'));
  lines.push(link('Risk Spots', 'risk-spots.md'));
  lines.push(link('Open Questions', 'open-questions.md'));

  lines.push('', '---', '', '_Generated by `wize-document-project`._', '');

  const file = path.join(dir, 'index.md');
  fs.writeFileSync(file, lines.join('\n'), 'utf-8');
  return { changed: true, written: ['index.md'] };
}

module.exports = { renderIndex, link, linkWithMarker };
