'use strict';

// install-script.js — generates a self-contained install script for the
// security-overlay pentest tools, using the CORRECT install source per
// tool. Most security tools are NOT in apt/brew: they are Go binaries
// shipped as GitHub releases. Treating everything as a PM package
// produces a script that fails (apt has no `gitleaks`/`nuclei`/`ffuf`/
// `osv-scanner`/`grype`). So each tool declares its real method:
//
//   - 'pm'       : available in the OS package manager (nmap, nikto, sqlmap, curl)
//   - 'github'   : a GitHub release asset (gitleaks, nuclei, ffuf, osv-scanner)
//   - 'script'   : an official installer script (grype)
//
// The generated bash script is idempotent and installs only what's missing.

const HEADER = `#!/usr/bin/env bash
# security-overlay — install pentest tools
# Generated by wize-sec-preflight. Safe to re-run (idempotent).
#
# Most of these tools are NOT in apt/brew — they are GitHub release
# binaries. This script installs each from its correct source.
# GitHub binaries go to ~/.local/bin (no sudo needed for those).
set -euo pipefail

LOCAL_BIN="\${HOME}/.local/bin"
mkdir -p "\${LOCAL_BIN}"
case ":\${PATH}:" in
  *":\${LOCAL_BIN}:"*) : ;;
  *) echo "NOTE: add \${LOCAL_BIN} to your PATH (e.g. in ~/.bashrc):"
     echo '      export PATH="$HOME/.local/bin:$PATH"' ;;
esac

# Detect arch for GitHub release downloads.
ARCH="$(uname -m)"
case "\${ARCH}" in
  x86_64|amd64) GH_ARCH="amd64"; GH_ARCH_ALT="x64" ;;
  aarch64|arm64) GH_ARCH="arm64"; GH_ARCH_ALT="arm64" ;;
  *) GH_ARCH="amd64"; GH_ARCH_ALT="x64" ;;
esac
OS_LC="$(uname -s | tr '[:upper:]' '[:lower:]')"

# Helper: download a tar.gz GitHub release and install one binary from it.
gh_targz() { # $1=url $2=binary-name-inside-archive
  local url="$1" bin="$2" tmp
  tmp="$(mktemp -d)"
  echo "  ↓ \${bin} <- \${url}"
  curl -fsSL "\${url}" -o "\${tmp}/a.tgz"
  tar -xzf "\${tmp}/a.tgz" -C "\${tmp}"
  install -m 0755 "\${tmp}/\${bin}" "\${LOCAL_BIN}/\${bin}"
  rm -rf "\${tmp}"
}

gh_zip() { # $1=url $2=binary-name-inside-archive
  local url="$1" bin="$2" tmp
  tmp="$(mktemp -d)"
  echo "  ↓ \${bin} <- \${url}"
  curl -fsSL "\${url}" -o "\${tmp}/a.zip"
  unzip -q -o "\${tmp}/a.zip" -d "\${tmp}"
  install -m 0755 "\${tmp}/\${bin}" "\${LOCAL_BIN}/\${bin}"
  rm -rf "\${tmp}"
}
`;

// Per-tool install recipe. Versions are pinned to known-good releases; the
// user can bump them. {GH_ARCH}/{GH_ARCH_ALT}/{OS} are substituted by the
// bash script's own variables at run time (we emit them as shell vars).
const TOOL_RECIPES = {
  // --- package-manager tools ---
  nmap:   { via: 'pm' },
  nikto:  { via: 'pm' },
  sqlmap: { via: 'pm' },
  curl:   { via: 'pm' },

  // --- GitHub release binaries ---
  gitleaks: {
    via: 'github',
    // gitleaks_8.18.4_linux_x64.tar.gz  (note: x64/arm64, not amd64)
    cmd: 'gh_targz "https://github.com/gitleaks/gitleaks/releases/download/v8.18.4/gitleaks_8.18.4_${OS_LC}_${GH_ARCH_ALT}.tar.gz" gitleaks'
  },
  nuclei: {
    via: 'github',
    // nuclei_3.3.7_linux_amd64.zip
    cmd: 'gh_zip "https://github.com/projectdiscovery/nuclei/releases/download/v3.3.7/nuclei_3.3.7_${OS_LC}_${GH_ARCH}.zip" nuclei'
  },
  ffuf: {
    via: 'github',
    // ffuf_2.1.0_linux_amd64.tar.gz
    cmd: 'gh_targz "https://github.com/ffuf/ffuf/releases/download/v2.1.0/ffuf_2.1.0_${OS_LC}_${GH_ARCH}.tar.gz" ffuf'
  },
  'osv-scanner': {
    via: 'github',
    // osv-scanner_linux_amd64 (raw binary, not archived)
    cmd: 'echo "  ↓ osv-scanner"; curl -fsSL "https://github.com/google/osv-scanner/releases/download/v2.0.2/osv-scanner_${OS_LC}_${GH_ARCH}" -o "${LOCAL_BIN}/osv-scanner"; chmod 0755 "${LOCAL_BIN}/osv-scanner"'
  },

  // --- official installer script ---
  grype: {
    via: 'script',
    cmd: 'curl -fsSL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b "${LOCAL_BIN}"'
  }
};

const TOOL_URLS = {
  nmap: 'https://nmap.org/download.html',
  nuclei: 'https://github.com/projectdiscovery/nuclei',
  gitleaks: 'https://github.com/gitleaks/gitleaks',
  'osv-scanner': 'https://github.com/google/osv-scanner',
  grype: 'https://github.com/anchore/grype',
  nikto: 'https://github.com/sullo/nikto',
  sqlmap: 'https://github.com/sqlmapproject/sqlmap',
  ffuf: 'https://github.com/ffuf/ffuf'
};

const PM_INSTALL = {
  apt:        (pkgs) => `sudo apt-get update && sudo apt-get install -y ${pkgs.join(' ')}`,
  dnf:        (pkgs) => `sudo dnf install -y ${pkgs.join(' ')}`,
  pacman:     (pkgs) => `sudo pacman -Syu --noconfirm ${pkgs.join(' ')}`,
  zypper:     (pkgs) => `sudo zypper install -y ${pkgs.join(' ')}`,
  apk:        (pkgs) => `sudo apk add ${pkgs.join(' ')}`,
  brew:       (pkgs) => `brew install ${pkgs.join(' ')}`,
  scoop:      (pkgs) => `scoop install ${pkgs.join(' ')}`,
  chocolatey: (pkgs) => `choco install -y ${pkgs.join(' ')}`
};

function generateInstallScript(preflight) {
  const { os, arch, packageManager, missing = [] } = preflight;
  const lines = [HEADER];

  lines.push(`# OS: ${os} (${arch})`);
  lines.push(`# Package manager: ${packageManager || 'none'}`);
  lines.push(`# Missing tools: ${missing.length === 0 ? '(none)' : missing.join(', ')}`);
  lines.push('');

  if (missing.length === 0) {
    lines.push('echo "All tools are already installed. Nothing to do."');
    return lines.join('\n');
  }

  // Bucket the missing tools by install method.
  const pmTools = [];
  const ghTools = [];
  const scriptTools = [];
  const unknownTools = [];
  for (const tool of missing) {
    const r = TOOL_RECIPES[tool];
    if (!r) { unknownTools.push(tool); continue; }
    if (r.via === 'pm') pmTools.push(tool);
    else if (r.via === 'github') ghTools.push(tool);
    else if (r.via === 'script') scriptTools.push(tool);
  }

  // 1. Package-manager tools (need a known PM).
  if (pmTools.length) {
    const pmFn = PM_INSTALL[packageManager];
    if (pmFn) {
      lines.push(`echo "==> Installing via ${packageManager}: ${pmTools.join(', ')}"`);
      lines.push(pmFn(pmTools));
    } else {
      lines.push(`echo "==> These need a package manager (none detected): ${pmTools.join(', ')}"`);
      for (const t of pmTools) lines.push(`echo "    ${t}: ${TOOL_URLS[t] || ''}"`);
    }
    lines.push('');
  }

  // 2. GitHub release binaries.
  if (ghTools.length) {
    lines.push(`echo "==> Installing GitHub-release binaries to \${LOCAL_BIN}: ${ghTools.join(', ')}"`);
    for (const t of ghTools) {
      lines.push(TOOL_RECIPES[t].cmd);
    }
    lines.push('');
  }

  // 3. Official installer scripts.
  if (scriptTools.length) {
    lines.push(`echo "==> Installing via official scripts: ${scriptTools.join(', ')}"`);
    for (const t of scriptTools) {
      lines.push(TOOL_RECIPES[t].cmd);
    }
    lines.push('');
  }

  // 4. Anything we don't have a recipe for.
  if (unknownTools.length) {
    lines.push(`echo "==> Manual install required for: ${unknownTools.join(', ')}"`);
    for (const t of unknownTools) {
      lines.push(`echo "    ${t}: ${TOOL_URLS[t] || 'https://www.google.com/search?q=' + encodeURIComponent(t + ' install')}"`);
    }
    lines.push('');
  }

  // Verification.
  lines.push('echo ""');
  lines.push('echo "==> Verifying..."');
  for (const tool of missing) {
    lines.push(`command -v ${tool} >/dev/null 2>&1 && echo "  ✓ ${tool}" || echo "  ✗ ${tool} (not on PATH yet)"`);
  }
  lines.push('');
  lines.push('echo "Done. If any tool shows ✗, ensure ~/.local/bin is on your PATH and re-open the shell."');
  lines.push('echo "Then run /wize-sec-pentest."');

  return lines.join('\n');
}

module.exports = { generateInstallScript, TOOL_RECIPES, TOOL_URLS, PM_INSTALL };
