'use strict';

// install-script.js — generates a self-contained install script for the
// security-overlay pentest tools. The script is OS-aware and PM-aware.
// It is idempotent: re-running on a host with some tools already
// installed only installs the missing ones.

const HEADER = `#!/bin/bash
# security-overlay — install pentest tools
# Generated by wize-sec-preflight. Safe to re-run (idempotent).
# To uninstall a tool, remove it with your package manager.
set -e
`;

const PM_MAP = {
  'apt': {
    name: 'apt',
    install: (pkgs) => `sudo apt-get update && sudo apt-get install -y ${pkgs.join(' ')}`,
    uninstall: (pkgs) => `sudo apt-get remove -y ${pkgs.join(' ')}`,
    list: (pkgs) => `dpkg -l | grep -E '${pkgs.join('|')}' || true`
  },
  'dnf': {
    name: 'dnf',
    install: (pkgs) => `sudo dnf install -y ${pkgs.join(' ')}`,
    uninstall: (pkgs) => `sudo dnf remove -y ${pkgs.join(' ')}`,
    list: (pkgs) => `rpm -q ${pkgs.join(' ')} || true`
  },
  'pacman': {
    name: 'pacman',
    install: (pkgs) => `sudo pacman -Syu --noconfirm ${pkgs.join(' ')}`,
    uninstall: (pkgs) => `sudo pacman -Rns --noconfirm ${pkgs.join(' ')}`,
    list: (pkgs) => `pacman -Q ${pkgs.join(' ')} || true`
  },
  'brew': {
    name: 'brew',
    install: (pkgs) => `brew install ${pkgs.join(' ')}`,
    uninstall: (pkgs) => `brew uninstall ${pkgs.join(' ')}`,
    list: (pkgs) => `brew list ${pkgs.join(' ')} || true`
  },
  'scoop': {
    name: 'scoop',
    install: (pkgs) => `scoop install ${pkgs.join(' ')}`,
    uninstall: (pkgs) => `scoop uninstall ${pkgs.join(' ')}`,
    list: (pkgs) => `scoop list ${pkgs.join(' ')} || true`
  },
  'chocolatey': {
    name: 'chocolatey',
    install: (pkgs) => `choco install -y ${pkgs.join(' ')}`,
    uninstall: (pkgs) => `choco uninstall -y ${pkgs.join(' ')}`,
    list: (pkgs) => `choco list --local-only --id ${pkgs.join('|')}`
  }
};

// Tool-name to package-name map. For apt/brew the names are usually the
// same; for others we map explicitly.
const PACKAGE_OVERRIDES = {
  'osv-scanner': { apt: 'osv-scanner', brew: 'osv-scanner' },
  'sqlmap':     { apt: 'sqlmap', brew: 'sqlmap' }
};

function packageName(tool, pm) {
  if (PACKAGE_OVERRIDES[tool] && PACKAGE_OVERRIDES[tool][pm]) return PACKAGE_OVERRIDES[tool][pm];
  return tool;
}

function generateInstallScript(preflight) {
  const { os, arch, packageManager, tools, missing = [] } = preflight;
  const lines = [HEADER];

  lines.push(`# OS: ${os} (${arch})`);
  lines.push(`# Package manager: ${packageManager || 'none'}`);
  lines.push(`# Missing tools: ${missing.length === 0 ? '(none)' : missing.join(', ')}`);
  lines.push('');

  if (missing.length === 0) {
    lines.push('echo "All tools are already installed. Nothing to do."');
    return lines.join('\n');
  }

  const pm = PM_MAP[packageManager];
  if (pm) {
    const packages = missing.map(t => packageName(t, packageManager));
    lines.push('echo "Installing missing tools via ' + pm.name + '..."');
    lines.push(pm.install(packages));
    lines.push('');
    lines.push('echo "Verifying installation..."');
    lines.push(pm.list(packages));
    lines.push('');
    lines.push('echo "Done. You can now run /wize-sec-pentest."');
  } else {
    // Manual install guide.
    lines.push('echo "No known package manager detected. Manual install required."');
    lines.push('echo "Visit the project pages for each tool:"');
    lines.push('');
    for (const tool of missing) {
      const url = TOOL_URLS[tool] || `https://www.google.com/search?q=${encodeURIComponent(tool + ' install')}`;
      lines.push(`echo "  ${tool}: ${url}"`);
    }
  }
  return lines.join('\n');
}

const TOOL_URLS = {
  nmap: 'https://nmap.org/download.html',
  nuclei: 'https://github.com/projectdiscovery/nuclei',
  gitleaks: 'https://github.com/gitleaks/gitleaks',
  'osv-scanner': 'https://github.com/osv-dev/osv-scanner',
  grype: 'https://github.com/anchore/grype',
  nikto: 'https://github.com/sullo/nikto',
  sqlmap: 'https://github.com/sqlmapproject/sqlmap',
  ffuf: 'https://github.com/ffuf/ffuf'
};

module.exports = { generateInstallScript, PM_MAP, packageName };
